name: env_setup
description: "this is for the environment setup"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  dio: ^5.4.3+1
  image_picker: ^1.1.1
  mime: ^1.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.3
  go_router: ^14.1.1
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.1
  flutter_inappwebview: ^5.8.0
  syncfusion_flutter_calendar: ^24.1.44
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  url_launcher: ^6.3.0
  skeletonizer: ^1.3.0
  syncfusion_flutter_maps: ^24.2.9
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  loader_overlay: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/env/dev.json
    - assets/env/uat.json
    - assets/env/prod.json
    - assets/env/qa.json
    # - assets/images/
    

  # example:
  # fonts:
  #   - family: GoogleSans
  #     fonts:
  #       - asset: assets/fonts/GoogleSans-Regular.ttf
  #         weight: 400
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
